export default {
  country_codes: {"global": "All region countries", "AFG": "Afghanistan", "ALB": "Albania", "DZA": "Algeria", "AND": "Andorra", "AGO": "Angola", "ATG": "Antigua and Barbuda", "ARG": "Argentina", "ARM": "Armenia", "AUS": "Australia", "AUT": "Austria", "AZE": "Azerbaijan", "BHS": "Bahamas", "BHR": "Bahrain", "BGD": "Bangladesh", "BRB": "Barbados", "BLR": "Belarus", "BEL": "Belgium", "BLZ": "Belize", "BEN": "Benin", "BTN": "Bhutan", "BOL": "Bolivia (Plurinational State of)", "BIH": "Bosnia and Herzegovina", "BWA": "Botswana", "BRA": "Brazil", "BRN": "Brunei Darussalam", "BGR": "Bulgaria", "BFA": "Burkina Faso", "BDI": "Burundi", "CPV": "Cabo Verde", "KHM": "Cambodia", "CMR": "Cameroon", "CAN": "Canada", "CAF": "Central African Republic", "TCD": "Chad", "CHL": "Chile", "CHN": "China", "COL": "Colombia", "COM": "Comoros", "COD": "Congo (Democratic Republic of the)", "COG": "Congo", "CRI": "Costa Rica", "HRV": "Croatia", "CUB": "Cuba", "CYP": "Cyprus", "CZE": "Czechia", "CIV": "Côte d'Ivoire", "DNK": "Denmark", "DJI": "Djibouti", "DMA": "Dominica", "DOM": "Dominican Republic", "ECU": "Ecuador", "EGY": "Egypt", "SLV": "El Salvador", "GNQ": "Equatorial Guinea", "ERI": "Eritrea", "EST": "Estonia", "SWZ": "Eswatini (Kingdom of)", "ETH": "Ethiopia", "FJI": "Fiji", "FIN": "Finland", "FRA": "France", "GAB": "Gabon", "GMB": "Gambia", "GEO": "Georgia", "DEU": "Germany", "GHA": "Ghana", "GRC": "Greece", "GRD": "Grenada", "GTM": "Guatemala", "GIN": "Guinea", "GNB": "Guinea-Bissau", "GUY": "Guyana", "HTI": "Haiti", "HND": "Honduras", "HKG": "Hong Kong,China (SAR)", "HUN": "Hungary", "ISL": "Iceland", "IND": "India", "IDN": "Indonesia", "IRN": "Iran (Islamic Republic of)", "IRQ": "Iraq", "IRL": "Ireland", "ISR": "Israel", "ITA": "Italy", "JAM": "Jamaica", "JPN": "Japan", "JOR": "Jordan", "KAZ": "Kazakhstan", "KEN": "Kenya", "KIR": "Kiribati", "KOR": "Korea (Republic of)", "KWT": "Kuwait", "KGZ": "Kyrgyzstan", "LAO": "Lao People's Democratic Republic", "LVA": "Latvia", "LBN": "Lebanon", "LSO": "Lesotho", "LBR": "Liberia", "LBY": "Libya", "LIE": "Liechtenstein", "LTU": "Lithuania", "LUX": "Luxembourg", "MDG": "Madagascar", "MWI": "Malawi", "MYS": "Malaysia", "MDV": "Maldives", "MLI": "Mali", "MLT": "Malta", "MHL": "Marshall Islands", "MRT": "Mauritania", "MUS": "Mauritius", "MEX": "Mexico", "FSM": "Micronesia (Federated States of)", "MDA": "Moldova (Republic of)", "MNG": "Mongolia", "MNE": "Montenegro", "MAR": "Morocco", "MOZ": "Mozambique", "MMR": "Myanmar", "NAM": "Namibia", "NPL": "Nepal", "NLD": "Netherlands", "NZL": "New Zealand", "NIC": "Nicaragua", "NER": "Niger", "NGA": "Nigeria", "MKD": "North Macedonia", "NOR": "Norway", "OMN": "Oman", "PAK": "Pakistan", "PLW": "Palau", "PSE": "Palestine,State of", "PAN": "Panama", "PNG": "Papua New Guinea", "PRY": "Paraguay", "PER": "Peru", "PHL": "Philippines", "POL": "Poland", "PRT": "Portugal", "QAT": "Qatar", "ROU": "Romania", "RUS": "Russian Federation", "RWA": "Rwanda", "KNA": "Saint Kitts and Nevis", "LCA": "Saint Lucia", "VCT": "Saint Vincent and the Grenadines", "WSM": "Samoa", "STP": "Sao Tome and Principe", "SAU": "Saudi Arabia", "SEN": "Senegal", "SRB": "Serbia", "SYC": "Seychelles", "SLE": "Sierra Leone", "SGP": "Singapore", "SVK": "Slovakia", "SVN": "Slovenia", "SLB": "Solomon Islands", "ZAF": "South Africa", "SSD": "South Sudan", "ESP": "Spain", "LKA": "Sri Lanka", "SDN": "Sudan", "SUR": "Surivalue", "SWE": "Sweden", "CHE": "Switzerland", "SYR": "Syrian Arab Republic", "TJK": "Tajikistan", "TZA": "Tanzania (United Republic of)", "THA": "Thailand", "TLS": "Timor-Leste", "TGO": "Togo", "TON": "Tonga", "TTO": "Trinidad and Tobago", "TUN": "Tunisia", "TUR": "Turkey", "TKM": "Turkmenistan", "UGA": "Uganda", "UKR": "Ukraine", "ARE": "United Arab Emirates", "GBR": "United Kingdom", "USA": "United States", "URY": "Uruguay", "UZB": "Uzbekistan", "VUT": "Vanuatu", "VEN": "Venezuela (Bolivarian Republic of)", "VNM": "Viet Nam", "YEM": "Yemen", "ZMB": "Zambia", "ZWE": "Zimbabwe" },
  indicators: {
    23806: "Population with at least some secondary education(% ages 25 and older)",
    23906: "Population with at least some secondary education, female(% ages 25 and older)",
    24006: "Population with at least some secondary education, male(% ages 25 and older)",
    24106: "GDI: Mean years of schooling(females aged 25 years and above)",
    24206: "GDI: Mean years of schooling(males aged 25 years and above)",
    31706: "Share of seats in parliament(% held by women)",
    36806: "Adolescent birth rate(births per 1, 000 women ages 15 - 19)",
    38406: "MPI 2019: Multidimensional poverty index, (revised)",
    38506: "MPI 2019: Intensity of deprivation",
    38606: "MPI 2019: Headcount, percentage of population in multidimensional poverty, (revised)",
    38806: "MPI: Multidimensional poverty index rank",
    39006: "MPI: Percentage poor, national poverty line",
    43006: "Vulnerable employment(% of total employment)",
    43606: "Internet users(% of population)",
    44206: "Population, total(millions)",
    45106: "Population, urban(%)",
    45806: "Primary school teachers trained to teach(%)",
    46006: "Mobile phone subscriptions(per 100 people)",
    46106: "Primary school dropout rate(% of primary school cohort)",
    46206: "Pupil - teacher ratio, primary school(pupils per teacher)",
    47906: "Population, median age(years)",
    48706: "Labour force participation rate, female(% ages 15 and older)",
    48806: "Labour force participation rate, male(% ages 15 and older)",
    49006: "Sex ratio at birth(male to female births)",
    52306: "Research and development expenditure(% of GDP)",
    52606: "Remittances, inflows(% of GDP)",
    53506: "Foreign direct investment, net inflows(% of GDP)",
    57206: "Infant mortality rate(per 1, 000 live births)",
    57506: "Under - five mortality rate(per 1, 000 live births)",
    57806: "Adult mortality rate, female(per 1, 000 people)",
    57906: "Adult mortality rate, male(per 1, 000 people)",
    58006: "HIV prevalence, adult(% ages 15 - 49)",
    61006: "Homicide rate(per 100, 000 people)",
    63106: "Population aged 15 - 64 years, both sexes",
    63206: "Gross enrolment ratio, primary(% of primary school - age population)",
    63306: "Gross enrolment ratio, secondary(% of secondary school - age population)",
    63406: "Gross enrolment ratio, tertiary(% of tertiary school - age population)",
    64306: "Infants lacking immunization, measles(% of one - year - olds)",
    64406: "Infants lacking immunization, DPT(% of one - year - olds)",
    65606: "Gross fixed capital formation(% of GDP)",
    67106: "IHDI: Income Gini coefficient",
    68606: "GII: Gender Inequality Index, value",
    68706: "GII: Gender Inequality Index, rank",
    69206: "HDI: Life expectancy at birth",
    69706: "HDI: Expected Years of Schooling(of children)",
    70506: "HDI: Education index, BYO",
    71406: "IHDI: Inequality - adjusted education index",
    71506: "IHDI: Inequality - adjusted life expectancy index",
    71606: "IHDI: Inequality - adjusted income index",
    73306: "IHDI: Inequality adjusted HDI rank",
    73506: "IHDI: Overall percentage loss",
    75906: "HDI: Expected Years of Schooling index rank",
    78406: "HDI: Life expectancy index rank",
    79906: "HDI: Education index, BYO, rank",
    80706: "MPI: Headcount Index, revised specification",
    80806: "MPI: Headcount, percentage of population in multidimensional poverty index rank",
    80906: "MPI: Index, BYO",
    81006: "MPI: Intensity of deprivation index, (BYO)",
    81106: "MPI: Intensity of deprivation index rank",
    86706: "HDI: Income index rank",
    87006: "HDI: Mean Years of Schooling index rank",
    89006: "Maternal mortality ratio(deaths per 100, 000 live births)",
    97106: "Fresh water withdrawals(% of total renewable water resources)",
    97306: "Natural resource depletion(% of GNI)",
    98306: "Children under - five who are stunted(moderate and severe)",
    99106: "Net official development assistance received(% of GNI)",
    100806: "Forest area(% of total land area)",
    101006: "MPI 2019: Population in severe poverty(headcount)",
    101406: "Adult literacy rate(% ages 15 and older)",
    101606: "IHDI: Inequality in education",
    101706: "IHDI: Inequality in income",
    101806: "IHDI: Inequality in life expectancy",
    102006: "MPI 2019: Headcount, number of people in multidimensional poverty(for the year of the survey)",
    103006: "HDI: Mean years of schooling(of adults)",
    103206: "HDI: Life expectancy index",
    103306: "HDI: Expected years of schooling index",
    103406: "HDI: Mean years of schooling(of adults) index",
    103606: "HDI: Income index",
    103706: "HDI: Education index",
    107006: "GII: GII index(BYO)",
    107806: "HDI: Income Index(BYO)",
    110806: "Net migration rate(per 1, 000 people)",
    110906: "Youth unemployment rate(% ages 15 - 24)",
    111106: "International inbound tourists(thousands)",
    111306: "Private capital flows(% of GDP)",
    112506: "Suicide rate, male(per 100, 000 people)",
    112606: "Suicide rate, female(per 100, 000 people)",
    117206: "IHDI: IHDI Index, (BYO)",
    117806: "MPI 2019: Contribution of Education",
    117906: "MPI 2019: Contribution of Health",
    118006: "MPI 2019: Contribution of standard of living",
    120606: "GDI: Life expectancy at birth, female",
    121106: "GDI: Life expectancy at birth, male",
    121206: "Dependency ratio, young age(0 - 14)(per 100 people ages 15 - 64)",
    122006: "Dependency ratio, old age(65 and older)(per 100 people ages 15 - 64)",
    123306: "GDI: Expected years of schooling, females",
    123406: "GDI: Expected years of schooling, males",
    123506: "GDI: Estimated GNI per capita(PPP), female",
    123606: "GDI: Estimated GNI per capita(PPP), male",
    123806: "Old age pension recipients(% of statutory pension age population)",
    127606: "Domestic credit provided by financial sector(% of GDP)",
    128106: "Mandatory paid maternity leave(days)",
    128306: "Prison population(per 100, 000 people)",
    132706: "Population, ages 65 and older(millions)",
    132806: "Population, under age 5(millions)",
    133006: "Gross enrolment ratio, pre - primary(% of preschool - age children)",
    133206: "Exports and imports(% of GDP)",
    135006: "IHDI: Coefficient of Human Inequality",
    135106: "IHDI: Income quintile ratio",
    135206: "IHDI: Palma ratio(Highest 10 % over lowest 40 %)",
    136706: "Gross domestic product(GDP) per capita(2011 PPP $)",
    136906: "GDI: Female HDI, Geometric",
    137006: "GDI: Male HDI, Geometric",
    137506: "HDI: Human development index(HDIg) value",
    137906: "GDI: Gender Development Index",
    138806: "IHDI: Inequality - adjusted HDI(geom) value",
    140606: "Total unemployment rate(% of labour force)",
    141706: "HDI: GNI per capita in PPP terms(constant 2011 international $)",
    142506: "MPI 2019: Population vulnerable to multidimensional poverty",
    143306: "Gross domestic product(GDP), total(2011 PPP $ billions)",
    146206: "HDI: HDI(3 - digit) rank",
    147206: "International student mobility(% of total tertiary enrolment)",
    147906: "Youth not in school or employment(% ages 15 - 24)",
    148206: "Labour force participation rate(% ages 15 and older)",
    148306: "Employment to population ratio(% ages 15 and older)",
    149206: "Government expenditure on education(% of GDP)",
    149406: "Homeless people due to natural disaster(average annual per million people)",
    150606: "Employment in agriculture(% of total employment)",
    150706: "Employment in services(% of total employment)",
    153706: "Working poor at PPP$3.20 a day(% of total employment)",
    163906: "Renewable energy consumption(% of total final energy consumption)",
    164206: "Change in forest area, 1990 / 2016",
    164406: "Adjusted net savings(% of GNI)",
    167106: "MPI: Population living below $1.90 PPP per day",
    167206: "2015 HDI(3 decimal places)",
    167406: "Violence against women ever experienced, intimate partner(%)",
    167506: "Violence against women ever experienced, nonintimate partner(%)",
    169706: "GD: Unemployment rate(total), female to male ratio",
    169806: "GD: Youth unemployment rate, female to male ratio",
    170006: "Concentration index - exports",
    174206: "Total debt service(% of exports of goods, services and primary income)",
    174306: "Fossil fuel energy consumption(% of total energy consumption)",
    174506: "Mortality rate attributed to household and ambient air pollution(per 100, 000 population)",
    174606: "Mortality rate attributed to unsafe water, sanitation and hygiene(WASH) services(per 100, 000 population)",
    175006: "Female share of employment in senior and middle management(%)",
    175106: "Share of employment in nonagriculture, female(%)",
    175206: "Antenatal care coverage, at least one visit(%)",
    175506: "Contraceptive prevalence, any method(%)",
    175606: "Unmet need for family planning(%)",
    175706: "Account ownership at a financial institution or with a mobile - money - service provider, female(%)",
    175906: "Share of female science, mathematics, engineering, manufacturing and construction graduates at tertiary level(%)",
    176806: "Programme for International Student Assessment(PISA) score in science",
    176906: "Programme for International Student Assessment(PISA) score in reading",
    177006: "Programme for International Student Assessment(PISA) score in mathematics",
    177706: "Survival rate to the last grade of lower secondary general education, both sexes(%)",
    178106: "Internet users, female(% of population)",
    178306: "Gross capital formation(% of GDP)",
    179406: "Skilled labour force(% of labour force)",
    179706: "Education and health expenditure to military expenditure, ratio",
    181106: "Birth registration(% under age 5)[SDG]",
    181206: "Proportion of births attended by skilled health personnel[SDG]",
    181306: "Child labour(% ages 5 - 17)[SDG]",
    181406: "Child marriage, married by age 18(%)[SDG]",
    181506: "FGM / C prevalence among girls and women(%)[SDG]",
    181606: "Red List Index",
    181706: "Rural population with access to electricity(%)",
    181806: "Current health expenditure(% of GDP)",
    182106: "Malaria incidence rate(per 1, 000 population at risk)",
    182206: "Tuberculosis incidence rate(per 100, 000 people)",
    183206: "IHDI: Average annual change in overall loss in HDI due to inequality(imported)",
    183406: "MPI 2019: Headcount, number of people in multidimensinoal poverty(projection for 2017)",
    183506: "Share of graduates from STEM programmes in tertiary education who are female(%)",
    183706: "Share of graduates from STEM programmes in tertiary education who are male(%)",
    183806: "MPI 2019: Inequality among the poor",
    183906: "Labour share of GDP, comprising wages and social protection transfers(%)",
    184006: "Proportion of informal employment in nonagricultural employment(% of total employment in nonagriculture)",
    185006: "Degraded land",
    185106: "Age - standarized mortality rate attributed to noncommunicable diseases, female",
    185206: "Age - standarized mortality rate attributed to noncommunicable diseases, male",
    185306: "Percentage of primary schools with access to the internet",
    185406: "Percentage of secondary schools with access to the internet",
    185506: "Population using at least basic drinking - water services(%)",
    185606: "Population using at least basic sanitation services(%)",
    186106: "IHDI: Income share held by richest 1 %",
    186606: "Carbon dioxide emissions per capita(tonnes)[SDG]",
    186706: "Carbon dioxide emissions per unit of GDP(kg of CO2 per constant 2010 United States dollars)[SDG]",
    186806: "Average annual change in the share of bottom 40 %",
    186906: "IHDI: Income share held by poorest 40 %",
    187006: "IHDI: Income share held by richest 10 %",
  },

  hdiSelect: [
    { key: 141706, value: "GNI per capita in PPP" },
    { key: 137506, value: "Human Development Index" },
    { key: 69206, value: "Life expectancy at birth" },
    { key: 69706, value: "Expected Years of Schooling"},
    { key: 103006, value: "Mean years of schooling"},
  ]
}